version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/load-cache:
          dependency-file: requirements-dev.txt
      - python/install-deps
      - python/install-deps:
          dependency-file: requirements-dev.txt
      - python/save-cache
      - python/save-cache:
          dependency-file: requirements-dev.txt
      - run:
          name: Install package
          command: pip install .
      - run:
          name: Test
          command: pytest tests

workflows:
  main:
    jobs:
      - build-and-test
